// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: Weather.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	WeatherService_ListWeather_FullMethodName = "/WeatherService/ListWeather"
)

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Weather service definition.
type WeatherServiceClient interface {
	// Sends a weather quest
	ListWeather(ctx context.Context, opts ...grpc.CallOption) (WeatherService_ListWeatherClient, error)
}

type weatherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherServiceClient(cc grpc.ClientConnInterface) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) ListWeather(ctx context.Context, opts ...grpc.CallOption) (WeatherService_ListWeatherClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WeatherService_ServiceDesc.Streams[0], WeatherService_ListWeather_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &weatherServiceListWeatherClient{ClientStream: stream}
	return x, nil
}

type WeatherService_ListWeatherClient interface {
	Send(*WeatherRequest) error
	CloseAndRecv() (*WeatherResponse, error)
	grpc.ClientStream
}

type weatherServiceListWeatherClient struct {
	grpc.ClientStream
}

func (x *weatherServiceListWeatherClient) Send(m *WeatherRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *weatherServiceListWeatherClient) CloseAndRecv() (*WeatherResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WeatherResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WeatherServiceServer is the server API for WeatherService service.
// All implementations must embed UnimplementedWeatherServiceServer
// for forward compatibility
//
// The Weather service definition.
type WeatherServiceServer interface {
	// Sends a weather quest
	ListWeather(WeatherService_ListWeatherServer) error
	mustEmbedUnimplementedWeatherServiceServer()
}

// UnimplementedWeatherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherServiceServer struct {
}

func (UnimplementedWeatherServiceServer) ListWeather(WeatherService_ListWeatherServer) error {
	return status.Errorf(codes.Unimplemented, "method ListWeather not implemented")
}
func (UnimplementedWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {}

// UnsafeWeatherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherServiceServer will
// result in compilation errors.
type UnsafeWeatherServiceServer interface {
	mustEmbedUnimplementedWeatherServiceServer()
}

func RegisterWeatherServiceServer(s grpc.ServiceRegistrar, srv WeatherServiceServer) {
	s.RegisterService(&WeatherService_ServiceDesc, srv)
}

func _WeatherService_ListWeather_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WeatherServiceServer).ListWeather(&weatherServiceListWeatherServer{ServerStream: stream})
}

type WeatherService_ListWeatherServer interface {
	SendAndClose(*WeatherResponse) error
	Recv() (*WeatherRequest, error)
	grpc.ServerStream
}

type weatherServiceListWeatherServer struct {
	grpc.ServerStream
}

func (x *weatherServiceListWeatherServer) SendAndClose(m *WeatherResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *weatherServiceListWeatherServer) Recv() (*WeatherRequest, error) {
	m := new(WeatherRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WeatherService_ServiceDesc is the grpc.ServiceDesc for WeatherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListWeather",
			Handler:       _WeatherService_ListWeather_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "Weather.proto",
}
